#!/bin/bash
dater=$(date -d "+7 days" '+%Y-%m-%d')
if [ "$(id -u)" -ne 0 ]; then
  echo "This script must be run with sudo or as root. Please try again."
  exit 1
fi

dir="$(dirname "$0")"

pacman -Syu --noconfirm
pacman -S nginx --noconfirm
pacman -S ufw --noconfirm
useradd -r -m -d /var/lib/webgen -s /usr/sbin/nologin webgen
mkdir /var/lib/webgen/bin
cp "$dir/Data/generate_index" /var/lib/webgen/bin/generate_index
cp "$dir/Data/generate_reveal" /var/lib/webgen/bin/generate_reveal
cp "$dir/setup-script" /var/lib/webgen/bin/setup-script
mkdir /var/lib/webgen/HTML
cp "$dir/Data/code.gif" /var/lib/webgen/HTML/code.gif
cp "$dir/Data/gameover.gif" /var/lib/webgen/HTML/gameover.gif
cp "$dir/Data/deadmen" /var/lib/webgen/bin/deadmen
cp "$dir/Data/deadman" /var/lib/webgen/bin/deadman
cp "$dir/Data/days-remaining.txt" /var/lib/webgen/bin/days-remaining.txt
chown -R webgen:webgen /var/lib/webgen
chmod -R 750 /var/lib/webgen
cp "$dir/Data/generate-index.service" /etc/systemd/system/generate-index.service
cp "$dir/Data/generate-index.timer" /etc/systemd/system/generate-index.timer
cp "$dir/Data/nginx.conf" /etc/nginx/nginx.conf
cp "$dir/Data/deadman.service" /etc/systemd/system/deadman.service
cp "$dir/Data/deadman@.timer" /etc/systemd/system/deadman@.timer
mkdir -p /etc/nginx/sites-available 
mkdir -p /etc/nginx/sites-enabled
cp "$dir/Data/system-info.conf" /etc/nginx/sites-available/system-info.conf
ln -s /etc/nginx/sites-available/system-info.conf /etc/nginx/sites-enabled/system-info.conf

systemctl enable --now generate-index.service
systemctl enable --now generate-index.timer
systemctl enable --now deadman.service
systemctl enable --now deadman@$dater.timer
systemctl enable --now nginx
systemctl enable --now ufw.service

ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw limit ssh
ufw allow http
ufw allow out 587
echo "y" | ufw enable
/var/lib/webgen/bin/setup-script


